"""I correspondence contracts; changed packets below are explicit hostile/test fixtures.

Fixtures replace sensory products only to exercise interpretation boundaries.
They are not claimed to have been generated by the unchanged physical provider.
Live provider contrasts and preservation tests are in the companion demo tests.
"""

from dataclasses import replace
import json

import pytest

from cca8_motor_contracts import MotorStreamRefV1
from cca8_navmap_kernel import NavPointV1
from nca8_sensorimotor_contracts import LocalTargetDispositionV1
from nca8_suckle import SuckleProfileV1
from nca8_suckle_demo import create_suckle_trial_v1
from nca8_suckle_outcomes import SuckleEndpointV1, SuckleIntervalEvidenceV1, SuckleOutcomeRuntimeV1


def prepared(case="nominal"):
    trial = create_suckle_trial_v1(case, outcomes_enabled=True)
    first = trial.focal_step()
    return trial, first, trial.core.suckle_outcomes


def buffered(ticks=12, case="nominal"):
    trial, first, owner = prepared(case)
    for _ in range(ticks):
        trial.advance_lower()
    return trial, first, owner, tuple(trial._suckle_intervals)


def snapshot(owner):
    return (tuple(x.as_dict() for x in owner.pending()), tuple(x.as_dict() for x in owner.history()), owner.retained_counts(),
            owner._last_cutoff, owner._last_interval, owner._last_command_id, owner._execution_end_tick,
            tuple((x.installed, x.command_intervals, x.ended_tick, x.end_reason) for x in owner._pending.values()))


def endpoint_fixture(intervals, transform):
    """Alter only the original event8 acquisition, not its prediction or controller."""
    result = []
    for item in intervals:
        deliveries, observations = [], []
        for sample in item.deliveries:
            visual = next((obs for obs in item.observations if obs.sample_id == sample.sample_id), None)
            if sample.event_tick == 8:
                sample, visual = transform(sample, visual)
            if sample is not None:
                deliveries.append(sample)
            if visual is not None:
                observations.append(visual)
        result.append(replace(item, deliveries=tuple(deliveries), observations=tuple(observations)))
    return tuple(result)


def test_H_default_has_no_I_owner_or_staged_intervals():
    trial = create_suckle_trial_v1()
    cycle = trial.focal_step()
    trial.advance_lower()
    assert trial.core.suckle_outcomes is None and cycle.suckle_correspondence is None
    assert "suckle_correspondence" not in cycle.as_dict() and trial._suckle_intervals == []


def test_registration_preserves_selected_preview_request_and_permission_before_movement():
    trial, first, owner = prepared()
    claim = first.suckle_correspondence.registration
    application = first.calculation.navigation.application
    assert trial.tick == 0 and trial.controller.installation_count == 1
    assert first.suckle_correspondence.outcomes == () and owner.history() == ()
    assert claim.preview is application.projection and claim.request is application.contribution
    assert claim.targets[0] is first.reservations[0].current
    assert (claim.due_tick, claim.expires_at_tick) == (8, 16)
    assert claim.as_dict()["predicts_latch_dwell_or_milk"] is False
    assert not claim.as_dict()["grants_motor_authority"]


def test_local_achievement_physical_seal_correspondence_and_latch_proof_are_separate():
    trial, first, owner, intervals = buffered()
    source = trial.core.feeding_detail.current
    assert trial.controller.reports[0].disposition.value == "achieved"
    assert trial.observer_oral_seal_body.sealed is True
    outcome = owner.consume_intervals(intervals, cutoff_tick=12)[0]
    assert outcome.status == "matched" and outcome.command_intervals == 6
    assert outcome.claim is first.suckle_correspondence.registration
    assert (outcome.evidence.feedback.event_tick, outcome.evidence.feedback.available_tick) == (8, 9)
    assert trial.latest_feedback.event_tick == 11 and trial.core.feeding_detail.current is source
    assert first.suckle_task.task.status == "active" and first.suckle_task.latch_samples == ()
    assert outcome.as_dict()["latch_task"] == "separate_H_two_sample_proof"
    assert outcome.as_dict()["causal_credit"] == "not_established"


@pytest.mark.parametrize("name", ["outcomes_enabled", "prediction_comparison_enabled", "enabled", "influence_enabled"])
@pytest.mark.parametrize("bad", [None, 0, 1, "false", (), [], 0.0])
def test_profile_switches_do_not_coerce(name, bad):
    with pytest.raises(TypeError):
        SuckleProfileV1(**{name: bad})


def test_comparison_off_requires_explicit_owner():
    with pytest.raises(ValueError):
        SuckleProfileV1(prediction_comparison_enabled=False)


@pytest.mark.parametrize("bad", [None, True, -1, 1.5, "12", 2**63])
def test_invalid_cutoff_is_atomic(bad):
    _, _, owner, intervals = buffered()
    before = snapshot(owner)
    with pytest.raises((TypeError, ValueError)):
        owner.consume_intervals(intervals, cutoff_tick=bad)
    assert snapshot(owner) == before


@pytest.mark.parametrize("bad", [None, 0, 1, "yes", []])
def test_runtime_requires_actual_boolean_comparison(bad):
    with pytest.raises(TypeError):
        SuckleOutcomeRuntimeV1(MotorStreamRefV1("test", 1), compare_predictions=bad)


@pytest.mark.parametrize("kind", ["order", "duplicate", "gap", "future", "foreign", "conflict", "copied_target", "foreign_command"])
def test_invalid_batch_cannot_partially_consume_exposure_or_evidence(kind):
    _, _, owner, intervals = buffered()
    batch, cutoff = list(intervals), 12
    if kind == "order":
        batch[0], batch[1] = batch[1], batch[0]
    elif kind == "duplicate":
        batch.insert(1, batch[0])
    elif kind == "gap":
        batch.pop(0)
    elif kind == "future":
        cutoff = 11
    elif kind == "foreign":
        batch[-1] = replace(batch[-1], deliveries=(replace(batch[-1].deliveries[0], stream=MotorStreamRefV1("foreign", 2)),), observations=())
    elif kind == "conflict":
        sample = replace(batch[2].deliveries[0], sample_id=batch[1].deliveries[0].sample_id)
        batch[2] = replace(batch[2], deliveries=(sample,), observations=(replace(batch[2].observations[0], sample_id=sample.sample_id),))
    elif kind == "copied_target":
        report = batch[0].reports[0]
        batch[0] = replace(batch[0], reports=(replace(report, committed_target=replace(report.committed_target)),))
    else:
        batch[0] = replace(batch[0], command=replace(batch[0].command, stream=MotorStreamRefV1("foreign", 2)))
    before = snapshot(owner)
    with pytest.raises((ValueError, TypeError)):
        owner.consume_intervals(tuple(batch), cutoff_tick=cutoff)
    assert snapshot(owner) == before


@pytest.mark.parametrize("kind", ["no_report", "stale_report", "terminal_report", "duplicate_report", "past_lease", "reused_command"])
def test_nonzero_closure_requires_current_original_permission(kind):
    _, _, owner, intervals = buffered()
    batch = list(intervals)
    if kind == "no_report":
        batch[0] = replace(batch[0], reports=())
    elif kind == "stale_report":
        batch[1] = replace(batch[1], reports=batch[0].reports)
    elif kind == "terminal_report":
        batch[0] = replace(batch[0], reports=(replace(batch[0].reports[0], disposition=LocalTargetDispositionV1.CANCELLED),))
    elif kind == "duplicate_report":
        batch[0] = replace(batch[0], reports=batch[0].reports * 2)
    elif kind == "past_lease":
        batch[8] = replace(batch[8], command=replace(batch[0].command, issued_tick=8, command_id=100))
    else:
        batch[1] = replace(batch[1], command=replace(batch[1].command, command_id=batch[0].command.command_id))
    before = snapshot(owner)
    with pytest.raises(ValueError):
        owner.consume_intervals(tuple(batch), cutoff_tick=12)
    assert snapshot(owner) == before


@pytest.mark.parametrize("sealed,contact,expected", [(True, True, "matched"), (False, True, "mismatch"),
                                                    (None, True, "unknown"), (True, False, "unknown"), (True, None, "unknown")])
def test_seal_is_not_inferred_from_closure_and_true_seal_requires_corresponding_touch(sealed, contact, expected):
    _, _, owner, intervals = buffered()
    def alter(f, v):
        return replace(f, oral=replace(f.oral, contact=contact), oral_seal=replace(f.oral_seal, sealed=sealed)), v
    outcome = owner.consume_intervals(endpoint_fixture(intervals, alter), cutoff_tick=12)[0]
    assert dict(outcome.relations)["closure"] == "matched"
    assert dict(outcome.relations)["seal"] == expected
    assert outcome.status == expected


@pytest.mark.parametrize("closure,expected", [(0.6, "matched"), (0.575, "matched"), (0.57499, "mismatch"), (0.7, "mismatch"), (None, "unknown")])
def test_original_fixed_closure_tolerance_not_local_attainment(closure, expected):
    _, _, owner, intervals = buffered()
    outcome = owner.consume_intervals(endpoint_fixture(intervals, lambda f, v: (replace(f, oral_seal=replace(f.oral_seal, closure=closure)), v)),
                                      cutoff_tick=12)[0]
    assert dict(outcome.relations)["closure"] == expected
    assert outcome.claim.preview.predicted_closure == 0.6


@pytest.mark.parametrize("offset,expected", [(0.0, "matched"), (0.0049, "matched"), (0.005, "matched"), (0.00501, "mismatch")])
def test_original_mouth_anchor_tolerance_is_frozen(offset, expected):
    _, _, owner, intervals = buffered()
    outcome = owner.consume_intervals(endpoint_fixture(intervals, lambda f, v: (replace(f, oral=replace(f.oral, extension_metres=0.1+offset)), v)),
                                      cutoff_tick=12)[0]
    assert dict(outcome.relations)["mouth_position"] == expected
    assert dict(outcome.residuals)["mouth_position"] == pytest.approx(offset)


@pytest.mark.parametrize("missing", ["position", "heading", "oral", "reach", "planar", "seal", "visual", "detail", "parent"])
def test_missing_coordinates_or_identity_cannot_be_filled_from_forecast(missing):
    _, _, owner, intervals = buffered()
    def alter(f, v):
        if missing == "position":
            return replace(f, planar=replace(f.planar, position=None)), replace(v, self_position=None)
        if missing == "heading":
            return replace(f, planar=replace(f.planar, heading_degrees=None)), v
        if missing == "oral":
            return replace(f, oral=None, oral_seal=None), v
        if missing == "reach":
            return replace(f, oral=replace(f.oral, extension_metres=None)), v
        if missing == "planar":
            return replace(f, planar=None, oral=None, oral_seal=None), None
        if missing == "seal":
            return replace(f, oral_seal=None), v
        if missing == "visual":
            return f, None
        region = "region_2" if missing == "detail" else "region_1"
        return f, replace(v, detections=tuple(d for d in v.detections if d.region_id != region))
    outcome = owner.consume_intervals(endpoint_fixture(intervals, alter), cutoff_tick=12)[0]
    assert outcome.status == "unknown"


@pytest.mark.parametrize("kind", ["category", "parent_category", "parent_distance"])
def test_contradicted_detail_identity_is_not_credited_to_the_original_claim(kind):
    _, _, owner, intervals = buffered()
    def alter(f, v):
        detections = []
        for detection in v.detections:
            if kind == "category" and detection.region_id == "region_2":
                detection = replace(detection, descriptor="object")
            if detection.region_id == "region_1":
                if kind == "parent_category":
                    detection = replace(detection, descriptor="hazard")
                elif kind == "parent_distance":
                    detection = replace(detection, position=NavPointV1(5, 0))
            detections.append(detection)
        return f, replace(v, detections=tuple(detections))
    outcome = owner.consume_intervals(endpoint_fixture(intervals, alter), cutoff_tick=12)[0]
    assert outcome.status == "identity_contradicted"


def test_narrowing_retains_original_forecast_and_proposed_authorized_meanings():
    _, first, owner, intervals = buffered(case="narrowed")
    claim = first.suckle_correspondence.registration
    before = claim.preview.as_dict()
    outcome = owner.consume_intervals(intervals, cutoff_tick=12)[0]
    assert claim.preview.predicted_closure == 0.6 and claim.targets[0].target.endpoint == pytest.approx(0.3)
    assert claim.authorization_status == "materially_narrowed" and claim.request.desired_closure == 0.6
    assert outcome.status == "partly_matched" and claim.preview.as_dict() == before
    assert dict(outcome.relations)["seal"] == dict(outcome.relations)["closure"] == "unevaluable_authorization"
    assert dict(outcome.residuals)["closure"] == pytest.approx(0.3)


@pytest.mark.parametrize("cancel_tick,expected", [(0, "cancelled"), (2, "interrupted"), (8, "matched"), (9, "matched")])
def test_cancellation_preserves_realized_endpoint_obligation(cancel_tick, expected):
    trial, _, owner = prepared()
    for _ in range(cancel_tick):
        trial.advance_lower()
    trial.cancel()
    while trial.tick < 12:
        trial.advance_lower()
    outcome = owner.consume_intervals(tuple(trial._suckle_intervals), cutoff_tick=12)[0]
    assert outcome.status == expected and outcome.command_intervals == min(cancel_tick, 6)


def test_no_command_means_no_execution_credit_even_when_sensed_relations_match():
    _, _, owner, intervals = buffered()
    outcome = owner.consume_intervals(tuple(replace(i, command=None) for i in intervals), cutoff_tick=12)[0]
    assert outcome.status == "observed_without_command" and outcome.command_intervals == 0
    assert dict(outcome.relations)["closure"] == "matched" and outcome.installed


@pytest.mark.parametrize("kind", ["copied_binding", "changed_request", "foreign", "wrong_tick", "duplicate", "wrong_family"])
def test_registration_rejects_changed_original_identity_atomically(kind):
    trial, first, _ = prepared()
    owner = SuckleOutcomeRuntimeV1(MotorStreamRefV1("foreign", 2) if kind == "foreign" else trial.latest_feedback.stream)
    owner.consume_intervals((), cutoff_tick=0)
    app, proposal, targets = first.calculation.navigation.application, first.calculation.proposal, tuple(r.current for r in first.reservations)
    before = snapshot(owner)
    with pytest.raises((TypeError, ValueError, RuntimeError)):
        if kind == "copied_binding":
            targets = (replace(targets[0], target=replace(targets[0].target)),)
        elif kind == "changed_request":
            proposal = replace(proposal, request=replace(proposal.request))
        elif kind == "wrong_tick":
            targets = (replace(targets[0], committed_tick=1),)
        elif kind == "duplicate":
            claim = owner.register(app, proposal, targets)
            owner.installed(claim, at_tick=0)
            before = snapshot(owner)
        elif kind == "wrong_family":
            app = None
        owner.register(app, proposal, targets)
    assert snapshot(owner) == before


@pytest.mark.parametrize("field", ["task_id", "application_id", "stream"])
def test_wrong_task_application_generation_cannot_relabel_a_claim(field):
    _, first, _ = prepared()
    claim = first.suckle_correspondence.registration
    value = MotorStreamRefV1("foreign", 2) if field == "stream" else "different_identity"
    with pytest.raises(ValueError):
        replace(claim, request=replace(claim.request, origin=replace(claim.request.origin, **{field: value})))


def test_description_copy_cannot_install_and_uninstalled_targets_cannot_gain_exposure():
    trial, first, _ = prepared()
    owner = SuckleOutcomeRuntimeV1(trial.latest_feedback.stream)
    owner.consume_intervals((), cutoff_tick=0)
    claim = owner.register(first.calculation.navigation.application, first.calculation.proposal, tuple(r.current for r in first.reservations))
    with pytest.raises(ValueError):
        owner.installed(replace(claim), at_tick=0)
    trial.advance_lower()
    with pytest.raises(ValueError):
        owner.consume_intervals(tuple(trial._suckle_intervals), cutoff_tick=1)
    owner.installed(claim, at_tick=0)
    with pytest.raises(ValueError):
        owner.installed(claim, at_tick=0)


@pytest.mark.parametrize("kind", ["visual_duplicate", "motor_duplicate", "unpaired", "position", "time", "frame", "sample", "mutable"])
def test_paired_acquisitions_require_exact_common_provenance(kind):
    _, _, _, intervals = buffered(3)
    item = intervals[1]
    sample, visual = item.deliveries[0], item.observations[0]
    with pytest.raises((ValueError, TypeError)):
        if kind == "visual_duplicate":
            replace(item, observations=(visual, visual))
        elif kind == "motor_duplicate":
            replace(item, deliveries=(sample, sample))
        elif kind == "unpaired":
            replace(item, deliveries=())
        elif kind == "position":
            SuckleEndpointV1(sample, replace(visual, self_position=NavPointV1(9, 9)))
        elif kind == "time":
            SuckleEndpointV1(sample, replace(visual, available_tick=visual.available_tick + 1))
        elif kind == "frame":
            SuckleEndpointV1(sample, replace(visual, frame_id="scene_xy:other"))
        elif kind == "sample":
            SuckleEndpointV1(sample, replace(visual, sample_id=99))
        else:
            replace(item, deliveries=list(item.deliveries))


@pytest.mark.parametrize("conflict", [False, True])
def test_repeated_endpoint_is_not_new_experience_and_conflict_is_atomic(conflict):
    _, _, owner, intervals = buffered()
    batch = list(intervals)
    original = batch[8]
    sample = original.deliveries[0]
    if conflict:
        sample = replace(sample, oral_seal=replace(sample.oral_seal, sealed=False))
    batch[9] = replace(batch[9], deliveries=(*batch[9].deliveries, sample), observations=(*batch[9].observations, original.observations[0]))
    before = snapshot(owner)
    if conflict:
        with pytest.raises(ValueError):
            owner.consume_intervals(tuple(batch), cutoff_tick=12)
        assert snapshot(owner) == before
    else:
        assert len(owner.consume_intervals(tuple(batch), cutoff_tick=12)) == len(owner.history()) == 1
        before = snapshot(owner)
        with pytest.raises(ValueError):
            owner.consume_intervals(intervals, cutoff_tick=13)
        assert snapshot(owner) == before


def test_missing_original_endpoint_expires_unresolved_without_substituting_later_success():
    _, _, owner, intervals = buffered(16)
    assert owner.consume_intervals(endpoint_fixture(intervals, lambda f, v: (None, None)), cutoff_tick=16) == ()
    assert owner.pending() and not owner.history()
    result = owner.consume_intervals((SuckleIntervalEvidenceV1(16, None, (), (), ()),), cutoff_tick=17)[0]
    assert result.status == "expired_unresolved" and result.command_intervals == 6 and result.evidence is None


@pytest.mark.parametrize("available,expected", [(12, "matched"), (16, "matched"), (17, "expired_unresolved")])
def test_delayed_exact_event_uses_original_arrival_window(available, expected):
    _, _, owner, intervals = buffered(16)
    original = next(i for i in intervals if any(f.event_tick == 8 for f in i.deliveries))
    sample = replace(original.deliveries[0], available_tick=available)
    visual = replace(original.observations[0], available_tick=available)
    batch = list(endpoint_fixture(intervals, lambda f, v: (None, None)))
    if available <= 16:
        item = batch[available - 1]
        batch[available - 1] = replace(item, deliveries=(*item.deliveries, sample), observations=(*item.observations, visual))
        result = owner.consume_intervals(tuple(batch), cutoff_tick=16)[0]
    else:
        assert owner.consume_intervals(tuple(batch), cutoff_tick=16) == ()
        result = owner.consume_intervals((SuckleIntervalEvidenceV1(16, None, (), (sample,), (visual,)),), cutoff_tick=17)[0]
    assert result.status == expected


def test_stop_reports_uncertain_effects_instead_of_reclassifying_as_veto():
    _, _, owner, _ = buffered(2)
    owner.close(reason="physical_effect_unknown")
    outcome = owner.history()[0]
    assert outcome.status == "unresolved_stopped" and outcome.installed and not owner.pending()
    assert outcome.as_dict()["execution_certainty"] == "unknown_after_fault"
    before = snapshot(owner)
    owner.close(reason="physical_effect_unknown")
    assert snapshot(owner) == before
    with pytest.raises(ValueError):
        owner.consume_intervals((), cutoff_tick=12)


def test_diagnostic_export_is_detached_and_cannot_rewrite_historical_prediction():
    _, _, owner, intervals = buffered()
    before = snapshot(owner)
    for _ in range(4):
        value = owner.pending()[0].as_dict()
        value["original_preview"]["predicted_closure"] = 0
        json.dumps(value, allow_nan=False)
    assert snapshot(owner) == before
    assert owner.consume_intervals(intervals, cutoff_tick=12)[0].status == "matched"


def test_pending_overflow_refuses_without_eviction_with_explicit_full_owner_fixture():
    _, first, original_owner = prepared()
    owner = SuckleOutcomeRuntimeV1(original_owner.stream)
    owner.consume_intervals((), cutoff_tick=0)
    pending = next(iter(original_owner._pending.values()))
    owner._pending = {f"pending:{i}": replace(pending) for i in range(8)}
    before = snapshot(owner)
    with pytest.raises(OverflowError):
        owner.register(first.calculation.navigation.application, first.calculation.proposal, tuple(r.current for r in first.reservations))
    assert snapshot(owner) == before


def test_diagnostics_bound_is_separate_from_live_pending_ownership():
    _, _, owner, intervals = buffered()
    original = owner.consume_intervals(intervals, cutoff_tick=12)[0]
    for number in range(2, 41):
        owner._history.append(replace(original, number=number))
    assert len(owner.history()) == 32 and owner.history()[0].number == 9 and not owner.pending()


@pytest.mark.parametrize("bad", [None, True, [], (), "", "x" * 101])
def test_invalid_close_reason_does_not_mutate_owner(bad):
    _, _, owner = prepared()
    before = snapshot(owner)
    with pytest.raises(ValueError):
        owner.close(reason=bad)
    assert snapshot(owner) == before


def test_early_protection_in_same_batch_invalidates_later_forged_drive():
    _, _, owner, intervals = buffered()
    stopped = replace(intervals[0], command=None,
                      reports=(replace(intervals[0].reports[0], disposition=LocalTargetDispositionV1.INTERRUPTED),))
    before = snapshot(owner)
    with pytest.raises(ValueError):
        owner.consume_intervals((stopped, *intervals[1:]), cutoff_tick=12)
    assert snapshot(owner) == before


def test_protection_survives_retirement_of_its_pending_claim():
    _, _, owner, intervals = buffered()
    stopped = replace(intervals[1], command=None,
                      reports=(replace(intervals[1].reports[0], disposition=LocalTargetDispositionV1.INTERRUPTED),))
    assert owner.consume_intervals((intervals[0], stopped), cutoff_tick=2)[0].status == "interrupted"
    assert not owner.pending()
    before = snapshot(owner)
    with pytest.raises(ValueError):
        owner.consume_intervals(intervals[2:4], cutoff_tick=4)
    assert snapshot(owner) == before


@pytest.mark.parametrize("change", ["lease", "rate"])
def test_material_lease_or_rate_narrowing_retains_original_prediction(change):
    _, first, _ = prepared()
    claim = first.suckle_correspondence.registration
    target = claim.targets[0]
    local = replace(target.target, **({"lease_ticks": 4} if change == "lease" else {"max_rate": 0.5}))
    narrowed = replace(claim, targets=(replace(target, target=local),), compatible_relations=("mouth_position", "detail_anchor"),
                       unevaluable_relations=("closure", "seal"))
    assert narrowed.authorization_status == "materially_narrowed" and narrowed.preview is claim.preview
    assert narrowed.request is claim.request


def test_partial_task_forecast_is_not_mistaken_for_a_changed_local_goal():
    """Explicit contract fixture: a short forecast can coexist with the unchanged farther target.

    This tests relation semantics, not live selection of an early four-tick H
    application. The live H operation uses a shorter horizon only at its task tail.
    """
    from nca8_suckle_outcomes import _compare
    _, first, _, intervals = buffered()
    original = first.suckle_correspondence.registration
    preview = replace(original.preview, predicted_closure=0.4, horizon_ticks=4)
    request = replace(original.request, lease_ticks=4)
    target = replace(original.targets[0], target=replace(original.targets[0].target, lease_ticks=4))
    claim = replace(original, preview=preview, request=request, targets=(target,))
    assert claim.authorization_status == "authorized" and claim.preview.predicted_closure == 0.4
    assert claim.targets[0].target.endpoint == claim.request.desired_closure == 0.6
    item = next(i for i in intervals if any(f.event_tick == 4 for f in i.deliveries))
    endpoint = item.endpoints()[0]
    relations, _, _ = _compare(claim, endpoint)
    assert dict(relations)["seal"] == "not_predicted" and dict(relations)["closure"] == "matched"
